; 轻量版分流规则

[custom]

; 设置规则标志位

; 内网
ruleset=🎯 直连,[]GEOSITE,private
ruleset=🎯 直连,[]GEOIP,private,no-resolve

; 自定义
ruleset=✍️ 手动选择,https://gh-proxy.com/https://raw.githubusercontent.com/Burgess-T/OpenClash_Rules/main/rule/Custom_Proxy.list,86000
ruleset=🎯 直连,https://gh-proxy.com/https://raw.githubusercontent.com/Burgess-T/OpenClash_Rules/main/rule/Custom_Direct.list,28800 ;过期时间 8h

; 直连
ruleset=🎯 直连,clash-domain:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Domain.yaml,28800
ruleset=🎯 直连,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Classical_IP.yaml,28800
ruleset=🎯 直连,[]GEOSITE,google-cn
ruleset=🎯 直连,[]GEOSITE,cloudflare-cn
ruleset=🎯 直连,[]GEOSITE,category-games@cn
ruleset=🎯 直连,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Steam_CDN_Classical.yaml,28800
ruleset=🎯 直连,[]GEOSITE,category-game-platforms-download
ruleset=🎯 直连,[]GEOSITE,category-public-tracker

; 分流
ruleset=✍️ 手动选择,[]GEOSITE,github
ruleset=🎯 直连,[]GEOSITE,microsoft
ruleset=🇬 谷歌服务,[]GEOSITE,google
ruleset=🇬 谷歌服务,[]GEOIP,google,no-resolve
ruleset=🤖 AI服务,[]GEOSITE,category-ai-!cn
ruleset=🎮 Steam,[]GEOSITE,steam
ruleset=🎮 游戏平台,[]GEOSITE,category-games
ruleset=🇺🇸 美国,[]GEOSITE,meta
ruleset=🇼🇸 台湾,[]GEOSITE,bahamut
ruleset=🎓 学术期刊,[]GEOSITE,category-scholar-!cn
ruleset=🚄 测速工具,[]GEOSITE,category-speedtest
ruleset=💾 网盘下载,[]GEOSITE,category-netdisk-!cn
ruleset=💬 telegram,[]GEOIP,telegram,no-resolve
ruleset=✍️ 手动选择,[]GEOSITE,gfw

; 兜底
; 由于 OpenClash 使用的大陆白名单收录不全，此处留有 geoip:cn 作为国内 IP 兜底
; 经过测试，没有一次匹配到此规则，且 OpenClash 大陆白名单中自带的 Hackl0us-CN-CIDR 数据库已经包含此部分，移除：
; ruleset=🎯 直连,[]GEOIP,cn,no-resolve
; 由于 OpenClash 使用的大陆白名单收录不全，此处留有 geosite:cn 作为国内域名兜
; 经过测试，只有极小量的网站会匹配到这条规则，但其12万的规则数却极度影响了查询性能，实用性不佳：
ruleset=🎯 直连,[]GEOSITE,cn

; 没有任何匹配
ruleset=🐟 漏网之鱼,[]FINAL
; 设置规则标志位结束



;设置节点分组标志位
custom_proxy_group=✍️ 手动选择`select`[]🎯 直连`[]♻️ 自动选择`[]📉 低倍率`[]📈 高倍率`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇼🇸 台湾`.*
custom_proxy_group=♻️ 自动选择`url-test`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇼🇸 台湾`https://www.google.com/generate_204`300,2,50 ;每隔300秒测试一次，测速超时为2s，切换的延迟容差为50ms

custom_proxy_group=🇬 谷歌服务`select`[]✍️ 手动选择`[]♻️ 自动选择`[]🎯 直连`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇼🇸 台湾`
custom_proxy_group=🤖 AI服务`select`[]✍️ 手动选择`[]♻️ 自动选择`[]🎯 直连`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇼🇸 台湾`
custom_proxy_group=🎮 Steam`select`[]✍️ 手动选择`[]♻️ 自动选择`[]🎯 直连`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇼🇸 台湾`
custom_proxy_group=🎮 游戏平台`select`[]✍️ 手动选择`[]♻️ 自动选择`[]🎯 直连`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇼🇸 台湾`
custom_proxy_group=🎓 学术期刊`select`[]✍️ 手动选择`[]♻️ 自动选择`[]🎯 直连`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇼🇸 台湾`
custom_proxy_group=🚄 测速工具`select`[]✍️ 手动选择`[]♻️ 自动选择`[]🎯 直连`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇼🇸 台湾`
custom_proxy_group=💾 网盘下载`select`[]✍️ 手动选择`[]♻️ 自动选择`[]📉 低倍率`[]📈 高倍率`[]🎯 直连`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇼🇸 台湾`
custom_proxy_group=💬 telegram`select`[]✍️ 手动选择`[]♻️ 自动选择`[]📉 低倍率`[]📈 高倍率`[]🎯 直连`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇼🇸 台湾`
custom_proxy_group=🐟 漏网之鱼`select`[]✍️ 手动选择`[]♻️ 自动选择`[]📉 低倍率`[]📈 高倍率`[]🎯 直连`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`[]🇸🇬 新加坡`[]🇼🇸 台湾`

custom_proxy_group=📉 低倍率`url-test`(?:0\.[1-9]\d?\s*(?:x|X|倍|倍率)|(?:x|X|倍|倍率)\s*0\.[1-9]\d?)`https://www.google.com/generate_204`300,2,50
custom_proxy_group=📈 高倍率`url-test`(?:(?:1\.(?:0*[1-9]\d*)|[2-9]\d*(?:\.\d+)?))\s*(?:x|X|倍|倍率)|(?:x|X|倍|倍率)\s*(?:1\.(?:0*[1-9]\d*)|[2-9]\d*(?:\.\d+)?)`https://www.google.com/generate_204`300,2,50

custom_proxy_group=🇭🇰 香港`url-test`(🇭🇰|港|\bHK(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|hk|Hong Kong|HongKong|hongkong|HONG KONG|HONGKONG|深港|HKG|九龙|Kowloon|新界|沙田|荃湾|葵涌)`https://www.google.com/generate_204`300,2,50
custom_proxy_group=🇺🇸 美国`url-test`(🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|纽纽|亚特兰大|迈阿密|华盛顿|\bUS(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|United States|UnitedStates|UNITED STATES|USA|America|AMERICA|JFK|EWR|IAD|ATL|ORD|MIA|NYC|LAX|SFO|SEA|DFW|SJC)`https://www.google.com/generate_204`300,2,50
custom_proxy_group=🇯🇵 日本`url-test`(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|\bJP(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Japan|JAPAN|JPN|NRT|HND|KIX|TYO|OSA|关西|Kansai|KANSAI)`https://www.google.com/generate_204`300,2,50
custom_proxy_group=🇸🇬 新加坡`url-test`(🇸🇬|新加坡|坡|狮城|\bSG(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Singapore|SINGAPORE|SIN)`https://www.google.com/generate_204`300,2,50
custom_proxy_group=🇼🇸 台湾`url-test`(🇹🇼|🇼🇸|台|新北|彰化|\bTW(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Taiwan|TAIWAN|TWN|TPE|ROC)`https://www.google.com/generate_204`300,2,50


custom_proxy_group=🎯 直连`select`[]DIRECT
; 设置分组标志位结束

;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true
